// <auto-generated />
namespace POS_System_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ItemCategoryClassChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemCategoryClassChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201802061452201_ItemCategoryClassChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
