// <auto-generated />
namespace POS_System_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsDelete_added_in_organization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsDelete_added_in_organization));
        
        string IMigrationMetadata.Id
        {
            get { return "201802081822534_IsDelete_added_in_organization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
